version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "Pass1921**"
            Set-Variable -Name "NGROK" -Value "1tGdkEwijsotwTa5QhaSHFC8uE6_7NkASAprwZzKzu2HUmevA"
            Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-adm64.zip -OutFile ngrok.zip
            ./ngrok.zip